import os
import sys

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__)))

# Add nodriver to context
# sys.path.append(os.path.join(BASE_DIR, "nodriver"))

config = {
    "log_dir_path": os.path.join(BASE_DIR, "logs\\"),
    "nodriver_env_path": os.path.join(BASE_DIR, "nodriver.env"),
    "browser": {
        "executable_path": os.path.join(BASE_DIR, "bin\\chrome.exe"),
        "profiles_dir_path": os.path.join(BASE_DIR, "profiles"),
        "args": [
            # "--auto-open-devtools-for-tabs",
            # "--disable-dev-shm-usage",
            "--no-sandbox",
            "--disable-gpu", 
        ],
    },
}

default_chrome_env = {
    "main": {
        # Debug logs
        "FINGERDOCK_DEBUG": False,

        # Detectors detection logs
        "DD_LOG_ENABLED": False,

        # Example: 126.0.6478.127
        # Set real ver if  None
        "CHROMIUM_VERSION": None,
    },
    "canvas2d": {
        # Example R/G/B value: 0.5 (from 0.000001 to 1.0)
        # Example noise: 0.001
        # Noise range: ?
        "CANVAS_NOISE_SK_COLOR4F_R": 0.000000,
        "CANVAS_NOISE_SK_COLOR4F_G": 0.000000,
        "CANVAS_NOISE_SK_COLOR4F_B": 0.000000,

        "CANVAS_NOISE_DRAW_TEXT_INTERNAL_X": 0.000,
        "CANVAS_NOISE_DRAW_TEXT_INTERNAL_Y": 0.000,

        "CANVAS_NOISE_DRAW_TEXT_INTERNAL_X_SCALE": 0.00000,
        "CANVAS_NOISE_DRAW_TEXT_INTERNAL_Y_SCALE": 0.00000,

        "CANVAS_NOISE_RADIAL_GRADIENT_X0": 0.00,
        "CANVAS_NOISE_RADIAL_GRADIENT_Y0": 0.00,
        "CANVAS_NOISE_RADIAL_GRADIENT_R0": 0.00,
        "CANVAS_NOISE_RADIAL_GRADIENT_X1": 0.00,
        "CANVAS_NOISE_RADIAL_GRADIENT_Y1": 0.00,
        "CANVAS_NOISE_RADIAL_GRADIENT_R1": 0.00,

        "CANVAS_NOISE_LINEAR_GRADIENT_X0": 0.00,
        "CANVAS_NOISE_LINEAR_GRADIENT_Y0": 0.00,
        "CANVAS_NOISE_LINEAR_GRADIENT_X1": 0.00,
        "CANVAS_NOISE_LINEAR_GRADIENT_Y1": 0.00,

        "CANVAS_NOISE_CONIC_GRADIENT_START_ANGLE": 0.00,
        "CANVAS_NOISE_CONIC_GRADIENT_CENTER_X": 0.00,
        "CANVAS_NOISE_CONIC_GRADIENT_CENTER_Y": 0.00,
    },

    "webgl": {
        "WEBGL_NOISE_SHADER_VERTEX_X": 0.0,
        "WEBGL_NOISE_SHADER_VERTEX_Y": 0.0,

        "WEBGL_NOISE_SHADER_FRAGMENT_R": 0.0,
        "WEBGL_NOISE_SHADER_FRAGMENT_G": 0.0,
        "WEBGL_NOISE_SHADER_FRAGMENT_B": 0.0,

        "WEBGL_PARAM_UNMASKED_VENDOR_WEBGL": None,
        "WEBGL_PARAM_UNMASKED_RENDERER_WEBGL": None,

        "WEBGL_VER1_EXTENSIONS": None,
        "WEBGL_VER2_EXTENSIONS": None,

        # WebGL1 params
        "WEBGL_PARAM_ALIASED_LINE_WIDTH_RANGE_MIN": None,
        "WEBGL_PARAM_ALIASED_LINE_WIDTH_RANGE_MAX": None,
        "WEBGL_PARAM_ALIASED_POINT_SIZE_RANGE_MIN": None,
        "WEBGL_PARAM_ALIASED_POINT_SIZE_RANGE_MAX": None,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_FLOAT_RANGE_MAX": None,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_FLOAT_RANGE_MIN": None,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_FLOAT_PRECISION": None,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_FLOAT_RANGE_MAX": None,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_FLOAT_RANGE_MIN": None,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_FLOAT_PRECISION": None,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_FLOAT_RANGE_MAX": None,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_FLOAT_RANGE_MIN": None,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_FLOAT_PRECISION": None,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_INT_RANGE_MAX": None,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_INT_RANGE_MIN": None,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_INT_PRECISION": None,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_INT_RANGE_MAX": None,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_INT_RANGE_MIN": None,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_INT_PRECISION": None,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_INT_RANGE_MAX": None,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_INT_RANGE_MIN": None,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_INT_PRECISION": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_FLOAT_RANGE_MAX": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_FLOAT_RANGE_MIN": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_FLOAT_PRECISION": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_FLOAT_RANGE_MAX": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_FLOAT_RANGE_MIN": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_FLOAT_PRECISION": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_FLOAT_RANGE_MAX": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_FLOAT_RANGE_MIN": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_FLOAT_PRECISION": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_INT_RANGE_MAX": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_INT_RANGE_MIN": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_INT_PRECISION": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_INT_RANGE_MAX": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_INT_RANGE_MIN": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_INT_PRECISION": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_INT_RANGE_MAX": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_INT_RANGE_MIN": None,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_INT_PRECISION": None,
        "WEBGL_PARAM_MAX_COMBINED_TEXTURE_IMAGE_UNITS": None,
        "WEBGL_PARAM_MAX_FRAGMENT_UNIFORM_VECTORS": None,
        "WEBGL_PARAM_MAX_RENDERBUFFER_SIZE": None,
        "WEBGL_PARAM_MAX_TEXTURE_IMAGE_UNITS": None,
        "WEBGL_PARAM_MAX_TEXTURE_SIZE": None,
        "WEBGL_PARAM_MAX_VARYING_VECTORS": None,
        "WEBGL_PARAM_MAX_VERTEX_TEXTURE_IMAGE_UNITS": None,
        "WEBGL_PARAM_MAX_VERTEX_UNIFORM_VECTORS": None,
        "WEBGL_PARAM_MAX_VIEWPORT_DIMS_W": None,
        "WEBGL_PARAM_MAX_VIEWPORT_DIMS_H": None,

        # WebGL2 params
        "WEBGL_PARAM_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS": None,
        "WEBGL_PARAM_MAX_COMBINED_UNIFORM_BLOCKS": None,
        "WEBGL_PARAM_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS": None,
        "WEBGL_PARAM_MAX_ELEMENT_INDEX": None,
        "WEBGL_PARAM_MAX_ELEMENTS_INDICES": None,
        "WEBGL_PARAM_MAX_FRAGMENT_INPUT_COMPONENTS": None,
        "WEBGL_PARAM_MAX_FRAGMENT_UNIFORM_BLOCKS": None,
        "WEBGL_PARAM_MAX_FRAGMENT_UNIFORM_COMPONENTS": None,
        "WEBGL_PARAM_MAX_SAMPLES": None,
        "WEBGL_PARAM_MAX_SERVER_WAIT_TIMEOUT": None,
        "WEBGL_PARAM_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS": None,
        "WEBGL_PARAM_MAX_UNIFORM_BUFFER_BINDINGS": None,
        "WEBGL_PARAM_MAX_VARYING_COMPONENTS": None,
        "WEBGL_PARAM_MAX_VERTEX_OUTPUT_COMPONENTS": None,
        "WEBGL_PARAM_MAX_VERTEX_UNIFORM_BLOCKS": None,
        "WEBGL_PARAM_MAX_VERTEX_UNIFORM_COMPONENTS": None,
    },

    "webaudio": {
        # Example `magnitude_scale` value: 0.000488281
        # Example noise: 0.000008281
        # Noise range: ?
        "AUDIO_NOISE_FFT_ANALYSIS_MAGNITUDE_SCALE": 0.00000,

        # Example `k` value: 0.8
        # Example noise: 0.1
        # Noise range: ?
        "AUDIO_NOISE_FFT_ANALYSIS_K": 0.00,
    },

    "navigator": {
        # Example real value: 5.10.0
        # Set real if empty
        # Posible values: ?
        "NAVIGATOR_AU_DATA_PLATFORM_VERSION": None, 

        # Example value 12
        # Set real if None
        # Posible values [2, 4, 8, 12, 20, ?]
        "NAVIGATOR_HARDWARE_CONCURRENCY": None,

        # Example value
        # Set real if None
        # Posible values [0.25, 0.5, 1, 2, 4, 8] 
        "NAVIGATOR_DEVICE_MEMORY": None, 
    },

    "geolocation": {
        # Example value: 37.77492
        "GEOLOCATION_LATITUDE": None,

        # Example value: -122.4194193
        "GEOLOCATION_LONGITUDE": None,

        # Example value: 320543.45523775835
        "GEOLOCATION_ACCURACY": None,
    },

    "device_status": {
        "DEVICE_STATUS_ESTIMATED_STORAGE": None,
        "DEVICE_STATUS_ESTIMATED_TEMPORARY_STORAGE": None,

        # Example value: 1.3006500
        "DEVICE_STATUS_TIME_RESOLUTION_NOISE_FACTOR": None,
    }
}

test_webgl_params = {
    "main": {
        "FINGERDOCK_DEBUG": True,
    },
    "webgl": {
        # WebGL1 params
        "WEBGL_PARAM_ALIASED_LINE_WIDTH_RANGE_MIN": 2,
        "WEBGL_PARAM_ALIASED_LINE_WIDTH_RANGE_MAX": 4,
        "WEBGL_PARAM_ALIASED_POINT_SIZE_RANGE_MIN": 3,
        "WEBGL_PARAM_ALIASED_POINT_SIZE_RANGE_MAX": 1025,

        "WEBGL_PARAM_VERTEX_SHADER_LOW_FLOAT_RANGE_MAX": 11,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_FLOAT_RANGE_MIN": 12,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_FLOAT_PRECISION": 13,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_FLOAT_RANGE_MAX": 14,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_FLOAT_RANGE_MIN": 15,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_FLOAT_PRECISION": 16,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_FLOAT_RANGE_MAX": 17,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_FLOAT_RANGE_MIN": 18,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_FLOAT_PRECISION": 19,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_INT_RANGE_MAX": 20,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_INT_RANGE_MIN": 21,
        "WEBGL_PARAM_VERTEX_SHADER_LOW_INT_PRECISION": 22,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_INT_RANGE_MAX": 23,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_INT_RANGE_MIN": 24,
        "WEBGL_PARAM_VERTEX_SHADER_MEDIUM_INT_PRECISION": 25,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_INT_RANGE_MAX": 26,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_INT_RANGE_MIN": 27,
        "WEBGL_PARAM_VERTEX_SHADER_HIGH_INT_PRECISION": 28,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_FLOAT_RANGE_MAX": 29,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_FLOAT_RANGE_MIN": 30,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_FLOAT_PRECISION": 31,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_FLOAT_RANGE_MAX": 32,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_FLOAT_RANGE_MIN": 33,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_FLOAT_PRECISION": 34,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_FLOAT_RANGE_MAX": 35,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_FLOAT_RANGE_MIN": 36,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_FLOAT_PRECISION": 37,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_INT_RANGE_MAX": 38,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_INT_RANGE_MIN": 39,
        "WEBGL_PARAM_FRAGMENT_SHADER_LOW_INT_PRECISION": 40,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_INT_RANGE_MAX": 41,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_INT_RANGE_MIN": 42,
        "WEBGL_PARAM_FRAGMENT_SHADER_MEDIUM_INT_PRECISION": 43,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_INT_RANGE_MAX": 44,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_INT_RANGE_MIN": 45,
        "WEBGL_PARAM_FRAGMENT_SHADER_HIGH_INT_PRECISION": 46,

        "WEBGL_PARAM_MAX_COMBINED_TEXTURE_IMAGE_UNITS": 65,
        "WEBGL_PARAM_MAX_FRAGMENT_UNIFORM_VECTORS": 4097,
        "WEBGL_PARAM_MAX_RENDERBUFFER_SIZE": 8193,
        "WEBGL_PARAM_MAX_TEXTURE_IMAGE_UNITS": 33,
        "WEBGL_PARAM_MAX_TEXTURE_SIZE": 8193,
        "WEBGL_PARAM_MAX_VARYING_VECTORS": 33,
        "WEBGL_PARAM_MAX_VERTEX_TEXTURE_IMAGE_UNITS": 33,
        "WEBGL_PARAM_MAX_VERTEX_UNIFORM_VECTORS": 4097,
        "WEBGL_PARAM_MAX_VIEWPORT_DIMS_W": 8193,
        "WEBGL_PARAM_MAX_VIEWPORT_DIMS_H": 8193,

        # WebGL2 params
        "WEBGL_PARAM_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS": 245761,
        "WEBGL_PARAM_MAX_COMBINED_UNIFORM_BLOCKS": 61,
        "WEBGL_PARAM_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS": 245761,
        "WEBGL_PARAM_MAX_ELEMENT_INDEX": 4294967295,
        "WEBGL_PARAM_MAX_ELEMENTS_INDICES": 2147483647,
        "WEBGL_PARAM_MAX_FRAGMENT_INPUT_COMPONENTS": 129,
        "WEBGL_PARAM_MAX_FRAGMENT_UNIFORM_BLOCKS": 15,
        "WEBGL_PARAM_MAX_FRAGMENT_UNIFORM_COMPONENTS": 16385,
        "WEBGL_PARAM_MAX_SAMPLES": 5, 
        "WEBGL_PARAM_MAX_SERVER_WAIT_TIMEOUT": 61,
        "WEBGL_PARAM_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS": 129,
        "WEBGL_PARAM_MAX_UNIFORM_BUFFER_BINDINGS": 73,
        "WEBGL_PARAM_MAX_VARYING_COMPONENTS": 125,
        "WEBGL_PARAM_MAX_VERTEX_OUTPUT_COMPONENTS": 129,
        "WEBGL_PARAM_MAX_VERTEX_UNIFORM_BLOCKS": 15,
        "WEBGL_PARAM_MAX_VERTEX_UNIFORM_COMPONENTS": 16385,
    }
}
